[Icon Theme]
Name=Lila
Inherits=hicolor,oxigen,faenza
Comment=Icon theme for all Gnu Linux  Operation Sistem ,by Cristian Pozzessere aka ilnanny
Directories=actions/scalable,apps/scalable,places/scalable


[actions/scalable]
Size=96
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512

[apps/scalable]
Size=96
Context=Apps
Type=Scalable
MinSize=8
MaxSize=512


[places/scalable]
Size=96
Context=Places
Type=Scalable
MinSize=8
MaxSize=512


